version: '3'
services:
  db:
    image: postgres:10.5
    env_file:
      - .env
    ports:
      - 5432:5432
  app:
    build: .
    command: ["./wait-for-it.sh", "db:5432", "--", "go", "run", "main.go"]
    env_file:
      - .env
    volumes:
      - .:/go/src/golang-csv-parser
    ports:
      - "80:8080"
    depends_on:
      - db
    links:
      - db